_LF_BLK: equ 0
_LF_WIDTH: equ 0
_LF_FENCE: equ 0
_LF_RZERO: equ 0
_LF_BASE: equ 0
_LF_STATE: equ 0
_LF_CSP: equ 0
_LF_RNUM: equ 0
_LF_SZERO: equ 0
_LF_OFFSE: equ 0
_LF_TIB: equ 0
_LF_INN: equ 0
_LF_CURR: equ 0
_LF_VOCL: equ 0
_LF_DP: equ 0
_LF_DPL: equ 0
_LF_CONT: equ 0
_LF_WARN: equ 0
_LF_SCR: equ 0
_LF_OUT: equ 0
_LF_HLD: equ 0
_LF_BLL: equ 0
_LF_XFIRS: equ 0
_LF_LA9EB: equ 0
_LF_WBFR: equ 0
_LF_ZERO: equ 0
_LF_LAA06: equ 0
_LF_XBUFS: equ 0
_LF_XLIMI: equ 0
_LF_LA9F4: equ 0
_LF_BSCR: equ 0
_LF_ONE: equ 0
_LF_XMINBU: equ 0
_LF_XMAXFI: equ 0
_LF_ANEXT: equ 0
_LF_XSFIL: equ 0
_LF_PAD: equ 0
_LF_ANN: equ 0
_LF_LA9FD: equ 0
_LF_CSLL: equ 0
_LF_WDSZ: equ 0
_LF_TRUE: equ 0
_LF_NEGTWO: equ 0
_LF_BBUF: equ 0
_LF_TWO: equ 0
_LF_EXIT: equ 0
_LF_IDO: equ 0
_LF_XDO: equ 0
_LF_XPULO: equ 0
_LF_TRAV: equ 0
_LF_WORD: equ 0
_LF_ONEWRD: equ 0
_LF_PWORD: equ 0
_LF_ENCL: equ 0
_LF_EXPECT: equ 0
_LF_PEXPEC: equ 0
_LF_TDROP: equ 0
_LF_RAT: equ 0
_LF_RPAT: equ 0
_LF_RFROM: equ 0
_LF_TOR: equ 0
_LF_DEPTH: equ 0
_LF_SPSTO: equ 0
_LF_SPAT: equ 0
_LF_PICK: equ 0
_LF_ROT: equ 0
_LF_QDUP: equ 0
_LF_DUPP: equ 0
_LF_DROP: equ 0
_LF_SWAP: equ 0
_LF_TDUP: equ 0
_LF_OVER: equ 0
_LF_NEGAT: equ 0
_LF_EQUAL: equ 0
_LF_ZGREA: equ 0
_LF_HEX: equ 0
_LF_DECIM: equ 0
_LF_USTAR: equ 0
_LF_DPLUS: equ 0
_LF_XORR: equ 0
_LF_ORR: equ 0
_LF_ANDD: equ 0
_LF_ZEQU: equ 0
_LF_TSLAS: equ 0
_LF_TSTAR: equ 0
_LF_TWOSUB: equ 0
_LF_TWOP: equ 0
_LF_ONESUB: equ 0
_LF_ONEP: equ 0
_LF_PM: equ 0
_LF_ABS: equ 0
;; _LF_NEGAT: equ 0
_LF_ZLESS: equ 0
_LF_SUBB: equ 0
_LF_MAX: equ 0
_LF_MIN: equ 0
_LF_PLUS: equ 0
_LF_GREAT: equ 0
_LF_LESS: equ 0
_LF_CMOVE: equ 0
_LF_DFIND: equ 0
_LF_PFIND: equ 0
_LF_ZBRAN: equ 0
_LF_BRAN: equ 0
_LF_USER: equ 0
_LF_LIT: equ 0
