	dw _test_0
	dw _test_PLUS
	dw _test_SWAP
	dw _test_LESS
	dw _test_GREAT
	dw _test_ROT
	dw _test_DOTCHEX
	dw _test_DOTHEX
	dw _test_DOCON
	dw _test_OVER
	dw _test_words
	dw _test_BRANCH
	dw _test_0BRANCH
	dw _test_PFIND
	dw _test_PFIND2
	dw _test_PFIND3
	dw _test_PFIND_NOTFOUND
	dw _test_AT_STORE
	dw _test_CAT
	dw _test_CMOVE
	dw _test_COUNT
	dw _test_CSTOR
	dw _test_PSTORE
	dw _test_ZLESS
	dw _test_NEGAT
	dw _test_PM
	dw _test_MIN
