	dw _test_0
	dw _test_PLUS
	dw _test_SWAP
	dw _test_LESS
	dw _test_GREAT
	dw _test_ROT
	dw _test_DOTCHEX
	dw _test_DOTHEX
	dw _test_DOCON
	dw _test_OVER
	dw _test_words
	dw _test_0BRANCH
	dw _test_PFIND
	dw _test_PFIND2
	dw _test_PFIN3
